# Generated by Django 4.2 on 2024-03-26 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodread', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchbookbykeyworditem',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_book_by_keyword_items', to='goodread.book', verbose_name='Book'),
        ),
        migrations.AlterField(
            model_name='searchgroupbykeyworditem',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_group_by_keyword_items', to='goodread.group', verbose_name='Group'),
        ),
    ]
